on: [push]
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.8.3', '8.8.4', '8.10.1', '8.10.2']
        cabal: ['3.2.0.0']
        os: [ubuntu-latest, macOS-latest]
    name: ${{ matrix.os }} - GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/cache@v1
        name: Cache ~/.cabal/store
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

      - uses: actions/checkout@v2

      - name: "Run HLint"
        run: curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s src test

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: |
          cabal build
          cabal test
