on: [push]
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ["8.8.4", "8.10.7", "9.0.2", "9.2.2"]
        cabal: ["3.2.0.0", "3.4.0.0", "3.6.0.0"]
        os: [ubuntu-latest]
    name: ${{ matrix.os }} - GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/cache@v3
        name: Cache ~/.cabal/store
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: setup-ffmpeg

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: |
          cabal build
          cabal test
