on: [push]
name: nix
jobs:
  haddock:
    runs-on: ubuntu-latest
    name: Nix build
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and generate haddock
        run: nix build

      - name: Deploy generated haddock to github pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result-doc/share/doc/pixiv-*/html
