on: [push]
name: nix
jobs:
  haddock:
    runs-on: ubuntu-latest
    name: Nix build
    steps:
      - uses: actions/checkout@v2
        with:
            # Nix Flakes doesn't work on shallow clones
            fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Build and generate haddock
      - run: |
          nix shell --command cabal haddock --haddock-html-location='https://hackage.haskell.org/package/$pkg-$version/docs' --haddock-hyperlink-source --haddock-quickjump
      - name: Deploy generated haddock to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist-newstyle/build/x86_64-linux/ghc-8.10.3/pixiv-*/doc/html/pixiv
