on: [push]
name: haddock
jobs:
  haddock:
    runs-on: ubuntu-latest
    name: Generate haddock
    steps:
      - uses: actions/cache@v1
        name: Cache ~/.cabal/store
        with:
          path: ~/.cabal/store
          key: cabal-cache
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: "8.10.2"
          cabal-version: "3.2.0.0"
      - run: cabal haddock
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist-newstyle/build/x86_64-linux/ghc-8.10.2/pixiv-*/doc/html/pixiv/
